Character jason marxsen
HayleyO/Fall2021_CSC403_Project pull request #16
Opened 2021-11-05 23:41 UTC by TempusEstNunc

Added a dictionary containing character ID and character objects corresponding to each character in the story

2021-11-06 19:07 UTC, HayleyO requested changes

2021-11-06 19:07 UTC, HayleyO commented on Project/MyGameLibrary/Character/CharacterCollection.cs
> +        private Dictionary<Items, int> dict3;
these need to be named better

2021-11-06 19:07 UTC, HayleyO commented on Project/Fall2020_CSC403_Project/TextEngine.cs
> +        private CharacterCollection Characters = new CharacterCollection();
Don't create the character collection object

2021-11-06 19:07 UTC, HayleyO commented on Project/MyGameLibrary/Character/CharacterCollection.cs
> +        private Character BurgerKing;
make these public and static

2021-11-06 19:07 UTC, HayleyO commented on Project/MyGameLibrary/Character/CharacterCollection.cs
> +        public Dictionary<characterID, Character> CharacterDictionary;
make this static

2021-11-06 19:07 UTC, HayleyO commented on Project/MyGameLibrary/Character/CharacterCollection.cs
> +        public CharacterCollection() {
turn this into a static function and call it on run of the program

2021-11-06 19:07 UTC, HayleyO commented on Project/MyGameLibrary/Character/characterID.cs
> +    public enum characterID
Change the name of this from characterID to CharacterID for naming convention

2021-11-08 17:01 UTC, hannahfolkertsma requested changes
Very small things overall to help improve readability 

The only major thing is the constructor. I'm not entirely confident in saying you can't have a static constructor, but it doesn't seem to make sense to me to have one. Overall it might be better to make it an initialize function in general.

2021-11-08 19:33 UTC, HayleyO approved these changes
Thanks so much! Sorry for being a pain great work

2021-11-08 19:33 UTC, merged