Created character class and function for updating love scores
HayleyO/Fall2021_CSC403_Project pull request #7
Opened 2021-10-29 21:02 UTC by TempusEstNunc

2021-10-29 21:05 UTC, hannahfolkertsma commented on Project/MyGameLibrary/Character/Character.cs
> +        public Dictionary<ItemID, LoveValue> ItemScores;
ItemID and LoveValue should be types (Items, int), and you can comment to specify what they are

2021-10-29 21:06 UTC, hannahfolkertsma commented on Project/MyGameLibrary/Character/Character.cs
> +        public void LoveUpdate(Character Person, int AdditionalScore)
dont need character person as a parameter, this would be character.loveupdate

2021-10-29 21:08 UTC, hannahfolkertsma commented on Project/MyGameLibrary/Character/Character.cs
> +        public Character(string name, int LScore, Dictionary<ItemID, LoveValue> dict)
change the function params to have items, int as well

2021-10-29 21:08 UTC, hannahfolkertsma submitted a review, later dismissed
see comments in the files

2021-10-29 22:01 UTC, HayleyO requested changes
See comments.

2021-10-29 22:01 UTC, HayleyO commented on Project/MyGameLibrary/Character/Character.cs
> +            SetLoveScore(LoveScore+ItemScores[item]);
When you update it to the C# built in getters and setters functionality you own't need this line you're just be able to add to the property to change it.

2021-11-01 23:23 UTC, HayleyO requested changes
Please address the C# setting and getting

2021-11-01 23:23 UTC, HayleyO commented on Project/MyGameLibrary/Character/Character.cs
>          public int GetLoveScore() {
Please use C#'s method of getting and setting, see previous comment as an example

2021-11-01 23:23 UTC, HayleyO commented on Project/MyGameLibrary/Character/Character.cs
> +        public void SetLoveScore(int LScore) {
put this in the c# setter as mentioned in previous comment

2021-11-02 18:26 UTC, HayleyO commented on Project/MyGameLibrary/Character/Character.cs
> +                return LoveScore;
Make sure you test all of this and this works.


Also, fix naming violations. 

The getter setter variable should be LoveScore and the internal private variable should be _LoveScore or something like that, please use naming conventions.

2021-11-02 21:13 UTC, HayleyO commented
Thanks for reaching out. I don't mind helping or clarifying if you need it on a comment, LGTM

2021-11-02 21:14 UTC, HayleyO approved these changes

2021-11-02 21:14 UTC, merged